### ISSUE TITLE
Not hosted under pytest-dev?

### ISSUE THREAD

**Issue by ssbarnea** [okken/pytest-skip-slow#2]
While this plugin looks interesting, I wonder why is not hosted under @pytest-dev 

PS. Some sort of CI/CD would also be useful.

**Comment by okken** [comment]
Hi @ssbarnea,
To answer your question:
- pytest has a [process for submitting a plugin to pytest-dev](https://docs.pytest.org/en/7.0.x/contributing.html?highlight=pytest%20dev#submitting-plugins-to-pytest-dev), and I haven't gone through that process.
- I think of pytest-dev plugins as those that get a lot of use. However, this is relatively new, and has 13 stars as of today. I'm not sure I would think of it as highly used yet.
- I might consider that in the future, however.

Regarding CI/CD, that would be useful. I already use GitHub actions on some projects, and adding it to this project would make sense. Adding a new issue and closing this.
