### ISSUE TITLE
Ability to run only slow tests

### ISSUE THREAD

**Issue by ssbarnea** [okken/pytest-skip-slow#3]
Current implementation allows to optionally enable slow tests but it does not allow to run only the slow tests.

**Comment by WillDaSilva** [comment]
Does running Pytest with the `-m slow` flag result in only the slow tests running? Maybe `-m slow --slow` would be required.

**Comment by okken** [comment]
Hi @ssbarnea,
@WillDaSilva is correct, adding `-m slow --slow` may seem odd, but is the preferred method to achieve running only slow tests.
This should be added to the Readme.

**Comment by okken** [comment]
Updated README.md
